### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by Busygind** [keksmd/ServerPart-Lab_6-#1]
https://github.com/keksmd/ServerPart-Lab_6-/blob/d53a6b96d74016f0f209aee930cf4330252bdce6/src/main/java/utilites/interfaces/Methods.java#L5

очень странная семантика интерфейса, абсолютно неочевидно для чего он нужен, что у него за аргументы и что он делает

**Comment by keksmd** [comment]
согласен,я его когда-то давно так назвал и так и не переименовал
сделал Callable
